import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Navbar from "@/Components/Common/Navbar";
import Providers from "@/Providers"; // <-- import your new Providers

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Random Apps",
  description: "Generated by Ajay Kumar"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} main-app-wrapper`}>
        <Providers>
          <Navbar />
          <div className="components-wrapper">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}